### ISSUE TITLE
how create a shared library ? in linux ? Thanks!

### ISSUE THREAD

**Issue by danieagle** [catid/wirehair#10]
(Whishlist) how create a shared lib ? in linux AMD64?

And Thanks for your Excelent Work! :-)

[]'s Daniel.

**Comment by catid** [comment]
I think this should work:
git clone https://github.com/catid/wirehair.git
cd wirehair
mkdir build
cd build
cmake ..
make -j

The static lib should be in the same folder as libwirehair.a if it builds..

**Comment by danieagle** [comment]
This new second pull request added cmake shared and install target and
a working example in Python Lang.

Thanks :-)

**Comment by catid** [comment]
Merged thank you!
