### ISSUE TITLE
Several cross-platform questions

### ISSUE THREAD

**Issue by seniorjoinu** [catid/wirehair#13]
Hello. Thank you for this amazing job.

I'm not an expert in FEC and math behind it, but I'm encouraged to use `wirehair` as a part of my reliable UDP project in Kotlin. As you might know, Kotlin is a very cross-platform language - everywhere Java can run Kotlin can run as well. And I want to take advantage of this property and make my project run on Linux, Windows, and Android.
So, my questions are:
1. What do you think, am I able to cross-compile `wirehair` to Windows and Android (I'm on ubuntu right now) using standard cross-compiling toolchains?
2. What do you think, will it work there?
3. Do you have any advice related to the topic?
4. If there is no possibility of running `wirehair` on Android, is there any other FEC implementations suitable for reliable UDP able to work fast in networks with very frequent retransmissions and providing comparable to `wirehair` performance you know?

Thanks in advance!

**Comment by catid** [comment]
For rUDP I'd recommend looking at Siamese and Tonk before settling on using
this project.  I feel those are more suitable

**Comment by seniorjoinu** [comment]
Yes, I've already looked at `Siamese` as well. 

Your quote: 
> For small loss count it's faster than Wirehair, and past a certain point (~10% loss) encode+decode time is longer than Wirehair.

**Comment by seniorjoinu** [comment]
`Wirehair` seems to be faster for a lossy network. Or you've meant something else?

**Comment by catid** [comment]
So the disadvantage of Wirehair for streaming data is that you'll need to
do some extra work to make it a generational encoder similar to Shorthair.
Otherwise it can only send one file per connection :)

The advantage of Siamese over Shorthair is that it is more efficient with
bandwidth.  You can just keep sending repair symbols and running normal ARQ
and eventually repair losses, without having to think about what generation
the repair symbols come from.  This also means less latency for repair for
Siamese versus Wirehair, because you just need to wait for the next repair
symbol to recover from a single loss, rather than waiting for the next
block to start.

**Comment by seniorjoinu** [comment]
My idea is to decouple Connections (some data like latency and retransmission rate which are used to calculate RTO and Transmission Window) and provide API to only send messages, not streams of data. So, each time you send some message, it gets split into small chunks (to handle MTU), then chunks sent to the receiver and ACK's awaited until RTO. Each ACK updates Connection, this leads to RTO and Window update. 
When a new message should be sent to that receiver, RTO and Window are just retrieved from the Connection object associated with that receiver and everything repeats.

I don't need streams and I'd like to implement something similar to classic UDP: you fill some packet with data, then send it to some address, but it always get received and you know it.

Maybe one file per Connection scheme fits me then?

**Comment by seniorjoinu** [comment]
Hm.. wait. Correct me if I'm wrong. You just said that I can send repair chunks constantly (and may be mixed with other repair packets related to some other data) until some moment I receive ACK that will mean that this data fully repaired on the remote host?

**Comment by catid** [comment]
Want to do a phone call?  May be easier to just answer questions in real
time :). My phone number is 1-404-561-1533

**Comment by catid** [comment]
Yeah totally if you are already considering each message separately and
they are independent (no head of line blocking) then you could run a
separate FEC codec for each message.

**Comment by seniorjoinu** [comment]
I'm sorry, but I live in Russia, St. Petersburg. It will cost us a lot с:
If you are busy right now or this topic is too complicated to answer in a short time - it's absolutely ok. I'm very interested in this piece of programming art, so I can wait as long as you need.

And maybe somebody else will be interested in this topic, so she can simply read this thread and get her questions answered.

**Comment by catid** [comment]
Yeah Siamese handles ARQ and FEC and memory buffers for data in transit
efficiently for TCP style communication with head of line blocking, which
may be different than your app

**Comment by catid** [comment]
Zoom chat?  https://us04web.zoom.us/j/889693661

**Comment by seniorjoinu** [comment]
For those from future: at the call, Christopher said that a) `wirehair` maybe fits better for my app, b) android builds are ok with the exception of some rare cases.
