### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by seniorjoinu** [catid/wirehair#15]
Hello. I'm experiencing this issue from time to time. Yesterday everything was fine (about 20 runs without any error) but today I only have something like 1 successful run out of 50 total. 

*Problem*
```
Thread 2 "java" received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:423
423	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
```
This error happens here `WirehairCodec.cpp:4078`:
```cpp
// Copy from the original file data
memcpy(data_out, src, copyBytes);
```

*Environment*
I've compiled the `master` branch with `c++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0` and `cmake 3.13.1`. I'm on ubuntu 18.04 (as you might guess) amd64. I'm calling your code from OpenJDK 8u191 using JNA.

*My quesses*
I'm absolutely newbie to C and all this pointer stuff, but after executing this line `WirehairCodec.cpp:4075`
```cpp
const uint8_t * GF256_RESTRICT src = _input_blocks + _block_bytes * block_id;
```
**in good scenario**  debugger says that value of the `src` is `""` (empty string)
**in bad scenario** debugger says that value of the `src` is `0x...` (some address)
The value of `_input_blocks`, `_block_bytes` and `block_id` is always the same type - address, int, int respectively.

**Comment by seniorjoinu** [comment]
UPD:
I only see this error when using Gradle to run my tests. But sometimes tests successfully complete.
When Gradle is not used - everything works perfectly.

**Comment by catid** [comment]
The memory provided as input must be aligned on ARM platform

**Comment by seniorjoinu** [comment]
I didn't get it. 
1. I'm not on ARM right now. 
2. Java handles alignment for me.

**Comment by catid** [comment]
Oh okay.  Is it the output or input buffer that is invalid on the segfault
line?  If it's the output, then make sure the output buffer has at least
copyBytes available

**Comment by seniorjoinu** [comment]
Input is invalid. As I said, sometimes it has an invalid value in it.

**Comment by catid** [comment]
It may be copying from the original input buffer?  Maybe the original data
is not accessible because the memory is not pinned and moved?

**Comment by seniorjoinu** [comment]
Yes, you were right. In Java message should be `DirectBuffer` or `Memory` instead of `ByteArray`

GC is evil c:
Thank you.
