### ISSUE TITLE
Adversarial erasure

### ISSUE THREAD

**Issue by foobar2019** [catid/wirehair#16]
If my understanding is correct, https://pdfs.semanticscholar.org/356f/0eaa61a54eda1adc99a794b28a55f8acc956.pdf applies to wirehair. If this is the case, then the statement:
>It may take N + 1 or N + 2 or more

Would deserve a clarification - is it possible to erase certain, rather "unfortunate" combination of symbols making the decoder fail even when getting far more than N symbols? Finding the exact trapping sets appears to be non-trivial in practice, but even with simple brute force, RaptorQ can be made to fail with just few hundred picked symbols even at 1/2 rate.

(solution seems to be to either keep PRNG secret from adversary, or use MDS)

**Comment by catid** [comment]
Yeah erasure codes as implemented here are not safe so you'd want to run it
over a secure tunnel.  You could drop every packet if you were a man in the
middle?

**Comment by foobar2019** [comment]
The attack vectors are more or less along the lines of "somebody being sneaky and DoSing replication of just the *right* par files. User gets 90%, but the archive can't be pieced together still...".

Public broadcast where censorship is costly, and precisely because it's costly, the censor would look at PRNG of LDPC matrix.

**Comment by catid** [comment]
Makes sense.  It would be a sort of amplification attack if data can be
selectively denied, but denying that data is expensive for some reason

**Comment by catid** [comment]
Because the tuning of the code is expensive, it makes switching up the PRNG
difficult.  So the best defense seems to be encryption that hides the
message identifiers, and randomly jumping the identifiers ahead to make
black box analysis harder

**Comment by foobar2019** [comment]
More or less. In my instance, my broadcast channel is something akin to torrent swarm with tricky incentives, where secrecy can't be afforded. There, this issue creates perverse incentive to withold combos of chunks in a tit-for-tat game. For now I'm using leopard to fix this, but that has separate issuess...

As for wirehair, I think something could be done about making finding the trapping sets combinatorially harder. Things will never be MDS, but could be made at least quasi-so by selecting seeds which are "hard to crack".

There's a body of research on this, as the problem is closely related to crap error floors of (standalone) LDPC.

**Comment by Bulat-Ziganshin** [comment]
why not use Leopard codec instead?

**Comment by foobar2019** [comment]
@Bulat-Ziganshin Performance. see https://github.com/catid/leopard/issues/14

**Comment by foobar2019** [comment]
A rough, but fairly simple workaround against the most trivial attacks: Assuming K and N are fairly high (10,000s...), lump 32 or so encoded() packets together per each "real" symbol, assuming that symbols are still binary erasure (par file either is or isnt). What this accomplishes is smoothing the packet weights, which adversary normally targets, but now has to censor far more to achieve same stopping power (higher DoS cost). This can be implemented completely on the user side, but introduces overhead.

A fancier approach would be for encode() to have xor weight smooth mode built in, and perhaps be somewhat more intelligent about it (lumping only 3-4 symbols at a time, with the soliton weights biased so as to fit smoothing).

**Comment by catid** [comment]
Clever!

**Comment by foobar2019** [comment]
Some ballparks - assuming base complexity is O(n) when running decoder state in parallel, and checking if row coming in turns out heavier (n is window within which you're erasing as adversary), the smoothing raises that to something like O(n^(x/2)), where x is number of grouped symbols to smooth (half of x because the search is always birthday one). This raises the bar from seconds to hours, which is good enough for me. In case someone can improve the attack, please (re)open the issue.
