### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by gitonio** [catid/wirehair#18]
Running into the following error while compiling a program that uses wirehair:

In file included from ./wirehair/cm256.h:32:0,
                 from ./fec.h:17,
                 from ./blockencodings.h:8,
                 from blockencodings.cpp:6:
./wirehair/gf256.h:70:14: fatal error: tmmintrin.h: No such file or directory
     #include <tmmintrin.h> // SSSE3: _mm_shuffle_epi8
              ^~~~~~~~~~~~~
compilation terminated.

This is on ubuntu.
Any help or quidance is appreciated.

**Comment by catid** [comment]
You probably need to add  -mssse3 to gcc

**Comment by gitonio** [comment]
Thanks for the quick response!

I tried:
sudo make CFLAGS='-mssse3'

That didn't change the output.

**Comment by catid** [comment]
Maybe `-march=native` ?

**Comment by gitonio** [comment]
Based on config.log output it looks like it is running with following flag:
  CXXFLAGS      = -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -Wno-implicit-fallthrough -march=native


I didn't mention that this is arm architecture. Are #define being correctly set for this architecture? 

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/7/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.4.0-1ubuntu118.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu/Linaro 7.4.0-1ubuntu118.04.1)

**Comment by catid** [comment]
Here's the switch that controls that:
https://github.com/catid/wirehair/blob/559de702b8f352e798776e0c3d7564761b70be49/gf256.h#L56

You could edit it to add your compiler's arm flag or add one of these to
your makefile

**Comment by gitonio** [comment]
Thank you. That worked.
