### ISSUE TITLE
Practicality of supporting more than 65535 blocks?

### ISSUE THREAD

**Issue by courtarro** [catid/wirehair#20]
I've got a 900MB file that I want to break into UDP-sized blocks that are ~1400 bytes in size. Thus, I need over 600,000 blocks, but the various block counters in the codec are limited to `uint16_t`. Actually this silently fails, which is probably a bug, but I was wondering whether it would be possible to support this, or if I'm asking for a horrible memory explosion in attempting to do that.

**Comment by catid** [comment]
Yeah it cannot do more than 65k.  You'd probably want to implement some
kind of generational code where the data is broken up into blocks that will
fit the codec, and each one is given a unique number
