### ISSUE TITLE
(wishlist) stream api

### ISSUE THREAD

**Issue by danieagle** [catid/wirehair#30]
Hi!
  Very Very Very Thanks for this lib.

  I am planning to use WireHair with files from hundreds of megabytes to tens of gigabytes or more,
ranging from 1 to 300 files simultaneously. this clearly does not fit in the server ram.

 Is there any way to not have to load entire files into ram?

Thanks!
Best Wishes, Daniel.

**Comment by catid** [comment]
I think you'd have to use swap for that or split it into separate pieces.  The row/column mixing travels all over the dataset.  Might be improved a bit but at the end of the day requires everything to produce the intermediate symbols and then produce output!

**Comment by danieagle** [comment]
Hi!
The internal data per si can be "splited" in less lenghty embedded chunks.
From your sugestion to other user , I'll test siameses pack and ir Cauchy Caterpillar.
Siameses package more advantage: I can use It as a internal format for files and to package data in udp datagrams.
.......
Note: Each day to  day I realize that You Catid is The Bether and The Best programmer in The fec area from more than 20+ years with extensive Internet log recomendations to use yours fec systems!

You have my personal Gratitude!!!
Very Very Very Thanks and Thanks to all yours continuous and hard work.

Best Wishes, Daniel.

**Comment by catid** [comment]
Wow that's nice of you to say thank you
