### ISSUE TITLE
Clarify on memory safety

### ISSUE THREAD

**Issue by sgdxbc** [catid/wirehair#46]
As partially mentioned in https://github.com/catid/wirehair/issues/2, I also notice that the message buffer must outlive encoder, but the block buffers are not necessarily to outlive the decoder. Can you confirm on this?

Also, I noticed that encoder seems to be capable to encode multiple blocks in parallel (i.e. through multithreading). (On the other hand decoding feels inherently sequential so I never attempt that.) Can you also clarify the thread safety properties? I am building a Rust binding for this library (https://github.com/sgdxbc/wirehair), and the language asks for explicit statement of lifetime and thread safety. Thanks.

**Comment by catid** [comment]
Ah, to be honest I forget since I worked on this like 10 years ago.  You might be better off just reading the code to find out or running some tests to see if it breaks.

**Comment by sgdxbc** [comment]
I see. Thanks.
