### ISSUE TITLE
Block duplication

### ISSUE THREAD

**Issue by sgdxbc** [catid/wirehair#47]
When I try out the README example, I notice that the encoded blocks may have duplicated content, and the total number of blocks with unique content is bounded.

The following results are with 2^16 bytes message and 2^6 bytes blocks, generating blocks with consecutive id that starts from an arbitrary id.
* When message content is all zero, all blocks are all zero
* When message content simply repeats one byte (e.g. through `memset` as in README), there are 128 unique blocks and each of them repeats one byte
  * The mapping between block id and content seems random with uniform distribution
* If I partially override the aforementioned message content by repeating another one byte, there may be 256 unique blocks by chance, but sometimes there are still 128 unique blocks
* With fully random message content such duplication is not observed
* The recovery does not behave differently when decoding blocks with duplicated or nonduplicated content

Is this expected? As defined in wikipedia, fountain codes should be "a class of [erasure codes](https://en.wikipedia.org/wiki/Erasure_codes) with the property that a potentially limitless [sequence](https://en.wikipedia.org/wiki/Sequence) of [encoding](https://en.wikipedia.org/wiki/Encoding) symbols". Well this library certainly can generate blocks for potentially limitless block id (2^32 is good enough for me), and according to the definition it's unclear that whether I should expect a potentially limitless sequence of block content. 

Also, does other rateless erasure codes have similar behavior? Is there any way to mitigate this? For example, is there any way to produce a sequence of block id for a given message so that those block id will generate blocks with distinct content? The general answer is probably no since theoretically the sequence cannot go beyound 128 id, but my use case is k=80-120 so it's still good to have. While there's a strawman solution that blindly generates first then discard duplicated blocks, it would be better to achieve it more efficiently. Thanks.

**Comment by catid** [comment]
Yes it treats the message contents as a black box and does not try to optimize for compressible input.  One way to take advantage of the type of input you described is to first compress the input before splitting it into pieces.  This is common practice for digital communication.  It's also good for encryption so the plaintext is harder to predict.

**Comment by sgdxbc** [comment]
Fair enough. Thanks.
