### ISSUE TITLE
android platform  armv7-a-neon issue

### ISSUE THREAD

**Issue by weiterlin** [catid/wirehair#5]
09-18 18:54:44.590 11127 11127 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-18 18:54:44.590 11127 11127 F DEBUG   : Build fingerprint: 'OneCloud/onething_onecloudpro/onething_onecloudpro:7.1.2/NHG47L/20180910:userdebug/test-keys'
09-18 18:54:44.590 11127 11127 F DEBUG   : Revision: '0'
09-18 18:54:44.591 11127 11127 F DEBUG   : ABI: 'arm'
09-18 18:54:44.591 11127 11127 F DEBUG   : pid: 11124, tid: 11124, name: gen_dcounts  >>> ./gen_dcounts <<<
09-18 18:54:44.591 11127 11127 F DEBUG   : signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xea2b105d
09-18 18:54:44.591 11127 11127 F DEBUG   :     r0 ea2b105d  r1 aad3c390  r2 00000000  r3 ea2b1059
09-18 18:54:44.591 11127 11127 F DEBUG   :     r4 0000000d  r5 0d000000  r6 148db80c  r7 0000df35
09-18 18:54:44.591 11127 11127 F DEBUG   :     r8 148db80c  r9 0021df35  sl 00000095  fp ea2b105d
09-18 18:54:44.591 11127 11127 F DEBUG   :     ip 00000057  sp ff8db3f8  lr 000000ad  pc aacd5170  cpsr 200f0010
09-18 18:54:44.623 11127 11127 F DEBUG   : 
09-18 18:54:44.623 11127 11127 F DEBUG   : backtrace:
09-18 18:54:44.623 11127 11127 F DEBUG   :     #00 pc 00006170  /mnt/nfs/android/gen_dcounts (gf256_muladd_mem+272)
09-18 18:54:44.648  4014  4111 W NativeCrashListener: Couldn't find ProcessRecord for pid 11124
09-18 18:54:44.653  3559  3559 W         : debuggerd: resuming target 11124
09-18 18:54:44.656  4014  4032 I BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)

**Comment by catid** [comment]
I think this is happening because you're running a tool that isn't designed
for mobile.  It is probably doing an unaligned access or something like
that.  Can you run that on an Intel processor instead?
